In [2]:
from wildlife_tools.data.dataset import WildlifeDataset
from wildlife_datasets import analysis, datasets, loader
import pandas as pd

d = datasets.ATRW('/Users/amee/Documents/code/master-thesis/datasets/ATRW')
d.df

,image_id,identity,path,bbox,keypoints,original_split
0,000408498f926bc6,16,atrw_detection_test/test/2639.jpg,"[654, 285, 743, 406]",NaN,test
1,0004d0b59e19461f,34,atrw_reid_train/train/001970.jpg,NaN,"[326, 77, 2, 283, 86, 2, 331, 141, 2, 210, 174...",train
2,000871c1fc726f0b,177,atrw_reid_train/train/004612.jpg,NaN,"[127, 57, 2, 144, 82, 2, 93, 149, 2, 264, 183,...",train
3,0031e80738c8832c,18,atrw_detection_test/test/1645.jpg,"[497, 292, 788, 493]",NaN,test
4,00411460f7c92d21,112,atrw_reid_test/test/000363.jpg,NaN,"[0, 0, 0, 537, 28, 2, 562, 77, 2, 437, 135, 2,...",test
...,...,...,...,...,...,...
5410,ffcf86475fe9dc67,180,atrw_detection_test/test/1108.jpg,"[118, 189, 1484, 807]",NaN,test
5411,ffd52f3c7e12435a,220,atrw_reid_train/train/000373.jpg,NaN,"[208, 1, 2, 237, 6, 2, 0, 0, 0, 191, 104, 2, 1...",train
5412,ffeabd223de0d4ea,60,atrw_reid_train/train/000575.jpg,NaN,"[55, 99, 2, 28, 80, 2, 2, 129, 2, 65, 184, 2, ...",train
5413,ffedf5be3a86e2ee,267,atrw_reid_train/train/002302.jpg,NaN,"[0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, ...",train
5414,ffeed84c7cb1ae7b,235,atrw_reid_test/test/001126.jpg,NaN,"[0, 0, 0, 843, 141, 2, 923, 275, 2, 599, 270, ...",test

In [ ]:
metadata = pd.read_csv('ExampleDataset/metadata.csv')
dataset = WildlifeDataset(metadata, 'ExampleDataset')

# View first image in the dataset.
image, label = dataset[0]